Cl/lending return process
hpi-swt2/bookkeeper-portal-red pull request #102
Opened 2022-11-29 15:51 UTC by Tonybodo

2022-11-30 09:10 UTC, janiswehen requested changes
Sieht erstmal super aus.
Hab noch ein paar kleine Sachen angemerkt. Außerdem sollte der eine Test nicht fehlschlagen.

2022-11-30 10:12 UTC, janiswehen requested changes
Sieht erstmal super aus.
Hab noch ein paar kleine Sachen angemerkt. Außerdem sollte der eine Test nicht fehlschlagen.

2022-11-30 10:12 UTC, janiswehen commented on app/controllers/items_controller.rb
> +    @item2 = Item.find(params[:item_id])
warum `@item2` und nicht `@item`

2022-11-30 10:12 UTC, janiswehen commented on app/models/item.rb
> +    return "Ausleihen" if (is_lendable)
Richtig wäre hier:
```Ruby
return "Zurückgeben" if is_lendable
return "Ausleihen" if is_borrowed_by(user)
"Nicht verfügbar"
```

2022-11-30 10:12 UTC, janiswehen commented on app/views/items/_form.html.erb
> +  <%= form.label :max_borrowing_period, style: "display: block" %>
Falsche Einrückung

2022-11-30 10:12 UTC, janiswehen commented on app/views/items/_item_largescreen.html.erb
> +                <div class="col-sm-3 ms-auto">
Das Badge kann man hier gut in eine Komponente auslagern

2022-11-30 10:12 UTC, janiswehen commented on app/views/items/_item_largescreen.html.erb
> +            <%= if current_user.has_lending_rights(@item)
Es wäre vielleicht auch gut, wenn man den Button auslagern.

2022-11-30 10:12 UTC, janiswehen commented on app/views/items/_item_smallscreen.html.erb
> +        <% if @item.is_lendable%>
Badge auslagern

2022-11-30 10:12 UTC, janiswehen commented on app/views/items/_item_smallscreen.html.erb
> -  <button class="btn btn-primary item-action-button"> Reservieren</button>
Button auslagern

2022-11-30 10:12 UTC, janiswehen commented on config/routes.rb
>    resources :items
Kann man die Zeile nicht weglasse?

2022-12-01 08:57 UTC, Tonybodo commented on app/models/item.rb
> +    return "Ausleihen" if (is_lendable)
Zurückgeben und Ausleihen tauschen

2022-12-01 08:59 UTC, janiswehen approved these changes
Sieht super aus

2022-12-01 08:59 UTC, merged

2022-12-08 15:51 UTC, johannaschlimme commented
closes #11 
closes #36