Add user membership management to group management
hpi-swt2/bookkeeper-portal-red pull request #219
Opened 2023-01-08 19:35 UTC by kbroschke

closes #106

2023-01-10 15:48 UTC, KiruChaff commented
We've tried implementing the feature through a form which is supposed to call the add_user method in the group controller. Unfortunately this method is not called through.

Maybe validate the resource and check if the form is correct

2023-01-11 09:56 UTC, TobiPeterG commented on app/controllers/groups_controller.rb
> +      user = User.where(email: params[:user]).first
should the parameter be called :email instad of :user?

2023-01-11 09:59 UTC, TobiPeterG commented
Unfortunately, I don't have a second user account to test this feature; is there any easy way to add a new user to the database?

2023-01-16 14:45 UTC, DieKautz commented
Whats still missing is
 * handling if the specified email belongs to no existing user and
 * shrinking the class length of the groups controller
    membership management maybe extracted to its own controller?

2023-01-22 13:03 UTC, kbroschke commented on app/views/groups/edit.html.erb
> +          <% if @user.admin_in?(@group) %>
The group controller assures that the edit page is only accessible to admins, so this will be always true.

2023-01-22 13:14 UTC, kbroschke commented on app/views/groups/edit.html.erb
> +          <% if @user.admin_in?(@group) %>
Should be resolved by aaf2b72

2023-01-22 13:51 UTC, kbroschke commented on app/controllers/groups_controller.rb
> +  end
Why do we need both variants?

2023-01-22 14:28 UTC, kbroschke commented on app/views/groups/edit.html.erb
> +          <% if @user.admin_in?(@group) %>
See also f4f01f2. Now CI is not failing anymore 👍🏻

2023-01-22 16:23 UTC, kbroschke commented
I implemented the idea of moving the user management logic into a separate controller. But there is still duplicated code left, because sharing code between controllers seems to be non-trivial. I already looked into using [Concerns](https://api.rubyonrails.org/v7.0.4/classes/ActiveSupport/Concern.html). Before using a separate controller, I also experimented with [other solutions](https://codeclimate.com/blog/7-ways-to-decompose-fat-activerecord-models/) to our problem. But in the end, just pointing the routes to the new `MembershipsController` was the easiest one to implement.

2023-01-25 12:05 UTC, TobiPeterG commented
When a user is not found, an alert should be shown instead of a notice. I added that.
Also there was an unused function added in the GroupsController, I removed it.
Might be useful for a refactor, but not this issue here.
Otherwise, it looks good!

2023-01-25 12:06 UTC, TobiPeterG approved these changes
If someone could quickly look over my changes, we're good to merge!

2023-01-25 15:19 UTC, kbroschke commented
I can't explicitly approve, but everything looks good to me. At least with refactorings tracked in #346 and in #353.
Maybe at least one additional person should review all changes (@KiruChaff or @DieKautz) because Tobias and I made so many recent changes.

2023-01-28 16:01 UTC, DieKautz requested changes

2023-01-29 15:00 UTC, Encotric approved these changes

2023-01-29 18:39 UTC, DieKautz approved these changes

2023-01-29 19:14 UTC, merged