hp/set item permissions
hpi-swt2/bookkeeper-portal-red pull request #223
Opened 2023-01-09 13:10 UTC by matveysiva

Aims to resolve Set permissions #153
Implemented permissions for book.
Todo: Adjust functionality to work with new items logic (#215)

2023-01-09 15:52 UTC, Yannis-Hofmann commented
The feature works. TODO: write tests (last commit contained some ideas but no reasonable tests yet)

2023-01-16 16:52 UTC, Yannis-Hofmann requested changes
Internationalization has to be added for permission level.

2023-01-17 14:47 UTC, Yannis-Hofmann submitted a review, later dismissed

2023-01-17 14:52 UTC, Yannis-Hofmann commented
Important: when this is merged on to main, we have to do a database migration so that a permission is created for all existing items giving the (yet to be implemented?) everybody_group manage rights to all items, so no items will be lost.
Our team will try to prepare this migration tomorrow.

2023-01-18 08:11 UTC, bweengener commented
> Important: when this is merged on to main, we have to do a database migration so that a permission is created for all existing items giving the (yet to be implemented?) everybody_group manage rights to all items, so no items will be lost.
> Our team will try to prepare this migration tomorrow.

@Yannis-Hofmann Have a look at my comment in the corresponding Issue for that, please. You will find the migration script there.

2023-01-18 13:53 UTC, Durborough approved these changes
Looks good to me, I just found an additional empty line. This could be removed for code cleanliness. Good job!

2023-01-18 13:53 UTC, Durborough commented on app/views/layouts/application.html.erb
> +
```suggestion
```

I suggest to removing this additional empty line.

2023-01-18 14:22 UTC, bweengener commented
I have now fixed Issue #276  and #277  as part of this PR as well. 

**Changelog**:
- Migration for `Everyone`-Group creation
- automatic adding of newly created users in `Everyone`-Group
- Migrations for Default-Memberships of existing accounts (required for `main` deployment)
- Visibilities for `personal_group` were removed from frontend and will be set automatically in backend from now on
- Integration of a migration script, so that already existing items (everyone, can_manage) are assigned 

**The current state on this branch resolves all blockers of permission-related stories.**

Please review as soon as possible to get this integrated into `dev` before deployment.

If anyone here can find the time, then transfer the Native SQL queries to AcrtiveRecord queries using the QueryBuilder.

cc: @Yannis-Hofmann , @WilliamBrandt

2023-01-18 14:26 UTC, Durborough approved these changes
Nicely done, some kinda complex stuff going on here and some comments would be appreciated next time, but the code seems to make sense and is readable.

2023-01-19 14:56 UTC, merged