feat: add personal group to user
hpi-swt2/bookkeeper-portal-red pull request #244
Opened 2023-01-11 15:56 UTC by konrad-gerlach

To test:
User `rails c` to delete your current user. (db migrate should have added personal group automatically,too)
Log in via OIDC.
User 'rails c' to check that your current user now has a personal group.

2023-01-12 17:14 UTC, johannaschlimme requested changes
Schöne und schnelle Umsetzung des Features! Ein paar Anmerkungen hab ich aber noch:

1. Es wäre schön, wenn ihr den Namen der Group auch im Frontend umbenennen könnt. Aktuell ist der Name der Group auf der Übersichtsseite aller Groups "personal_group".
2. @DefineDan @Alorcus Sollte die personal_group gelöscht werden können? Aktuell ist dies möglich. Ich denke mal, das sollte eher nicht möglich sein...
3. Aktuell ist es möglich, ein neues Membership zu einer personal_group zu erstellen, obwohl der User bereits in einer personal_group ist. Dies habt ihr auch getestet (user_spec.rb l.30). Wäre es nicht besser, dies direkt in der Erstellung des Memberships zu verbieten, sodass ein User wirklich nur in einer personal_group Mitglied sein kann?

Danke euch schon mal!

2023-01-12 19:11 UTC, DefineDan commented
> Schöne und schnelle Umsetzung des Features! Ein paar Anmerkungen hab ich aber noch:
> 
>     1. Es wäre schön, wenn ihr den Namen der Group auch im Frontend umbenennen könnt. Aktuell ist der Name der Group auf der Übersichtsseite aller Groups "personal_group".
> 
>     2. @DefineDan @Alorcus Sollte die personal_group gelöscht werden können? Aktuell ist dies möglich. Ich denke mal, das sollte eher nicht möglich sein...
> 
>     3. Aktuell ist es möglich, ein neues Membership zu einer personal_group zu erstellen, obwohl der User bereits in einer personal_group ist. Dies habt ihr auch getestet (user_spec.rb l.30). Wäre es nicht besser, dies direkt in der Erstellung des Memberships zu verbieten, sodass ein User wirklich nur in einer personal_group Mitglied sein kann?
> 
> 
> Danke euch schon mal!

Beide Punkte sind richtig, die personal Group sollte nicht gelöscht werden können und es sollten auch keine Mitglieder hinzugefügt werden. Wir hatten als POs auch schon darüber gesprochen und @Alorcus wollte dazu (Verwaltung der personal group) ein Ticket schreiben. In demTicket hier #179 geht es aber ja erstmal nur darum, diese anzulegen, sodass jeder User immerhin schonmal in einer personal Group ist.

2023-01-13 08:30 UTC, Alorcus commented
> > Schöne und schnelle Umsetzung des Features! Ein paar Anmerkungen hab ich aber noch:
> > ```
> > 1. Es wäre schön, wenn ihr den Namen der Group auch im Frontend umbenennen könnt. Aktuell ist der Name der Group auf der Übersichtsseite aller Groups "personal_group".
> > 
> > 2. @DefineDan @Alorcus Sollte die personal_group gelöscht werden können? Aktuell ist dies möglich. Ich denke mal, das sollte eher nicht möglich sein...
> > 
> > 3. Aktuell ist es möglich, ein neues Membership zu einer personal_group zu erstellen, obwohl der User bereits in einer personal_group ist. Dies habt ihr auch getestet (user_spec.rb l.30). Wäre es nicht besser, dies direkt in der Erstellung des Memberships zu verbieten, sodass ein User wirklich nur in einer personal_group Mitglied sein kann?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Danke euch schon mal!
> 
> @johannaschlimme Beide Punkte sind richtig, die personal Group sollte nicht gelöscht werden können und es sollten auch keine Mitglieder hinzugefügt werden. Wir hatten als POs auch schon darüber gesprochen und @Alorcus wollte dazu (Verwaltung der personal group) ein Ticket schreiben. In demTicket hier #179 geht es aber ja erstmal nur darum, diese anzulegen, sodass jeder User immerhin schonmal in einer personal Group ist.

Cool to see the personal groups! One of the last steps for a working permission system :D
@johannaschlimme the tickets #258 and #259 will solve your problem No. 2 and No. 3

2023-01-13 08:59 UTC, konrad-gerlach commented
> Schöne und schnelle Umsetzung des Features! Ein paar Anmerkungen hab ich aber noch:
> 
>     1. Es wäre schön, wenn ihr den Namen der Group auch im Frontend umbenennen könnt. Aktuell ist der Name der Group auf der Übersichtsseite aller Groups "personal_group".
> 
>     2. @DefineDan @Alorcus Sollte die personal_group gelöscht werden können? Aktuell ist dies möglich. Ich denke mal, das sollte eher nicht möglich sein...
> 
>     3. Aktuell ist es möglich, ein neues Membership zu einer personal_group zu erstellen, obwohl der User bereits in einer personal_group ist. Dies habt ihr auch getestet (user_spec.rb l.30). Wäre es nicht besser, dies direkt in der Erstellung des Memberships zu verbieten, sodass ein User wirklich nur in einer personal_group Mitglied sein kann?
> 
> 
> Danke euch schon mal!

Ich hatte unser Ticket als reines Backend Ticket interpretiert. Eigentlich sollten die Personal Groups vemutlich sowieso gar nicht im Frontend gelistet werden (damit man auch nicht in Versuchung kommt sie zu löschen).
Punkt 2: Das können wir Backend seitig glaube ich nicht so gut verhindern, aber wir können uns das nochmal anschauen.
Punkt 3 können wir auch mit validations umsetzen, genau wie wir verboten haben, dass eine Personal Group mehrere Nutzer haben kann.

2023-01-13 19:23 UTC, DefineDan commented
> > Schöne und schnelle Umsetzung des Features! Ein paar Anmerkungen hab ich aber noch:
> > ```
> > 1. Es wäre schön, wenn ihr den Namen der Group auch im Frontend umbenennen könnt. Aktuell ist der Name der Group auf der Übersichtsseite aller Groups "personal_group".
> > 
> > 2. @DefineDan @Alorcus Sollte die personal_group gelöscht werden können? Aktuell ist dies möglich. Ich denke mal, das sollte eher nicht möglich sein...
> > 
> > 3. Aktuell ist es möglich, ein neues Membership zu einer personal_group zu erstellen, obwohl der User bereits in einer personal_group ist. Dies habt ihr auch getestet (user_spec.rb l.30). Wäre es nicht besser, dies direkt in der Erstellung des Memberships zu verbieten, sodass ein User wirklich nur in einer personal_group Mitglied sein kann?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Danke euch schon mal!
> 
> Ich hatte unser Ticket als reines Backend Ticket interpretiert. Eigentlich sollten die Personal Groups vemutlich sowieso gar nicht im Frontend gelistet werden (damit man auch nicht in Versuchung kommt sie zu löschen). Punkt 2: Das können wir Backend seitig glaube ich nicht so gut verhindern, aber wir können uns das nochmal anschauen. Punkt 3 können wir auch mit validations umsetzen, genau wie wir verboten haben, dass eine Personal Group mehrere Nutzer haben kann.

@konrad-gerlach Are the changes requested are completely covered by the issues #258 and #259 ? I would consider this PR done, since it was only about creating the personal group, not how to manage it, you can move on to these new tickets if you want.

2023-01-13 22:39 UTC, johannaschlimme approved these changes
As Daniel already wrote, I agree that the newly created issues fully cover my feedback. I will merge this PR, but please limit deleting the personal group in the frontend asap so we don't have issues with users who no longer have a personal group :) I think if this is restricted in the frontend, there is also no need to add new validations for creation in the backend (regarding point 3).
Thanks everyone for the quick clarification!

2023-01-13 22:43 UTC, merged