Cl/owner return
hpi-swt2/bookkeeper-portal-red pull request #245
Opened 2023-01-11 16:18 UTC by Tonybodo

2023-01-11 16:31 UTC, Tonybodo commented
@DefineDan mir ist aufgefallen, das ich evtl. etwas falsch verstanden habe. In der jetzigen Implementierung gibt der Owner quasi das Item zurück, weil er ja auf Rückgabe drückt. Ist das so gewollt oder soll der user eingetragen werden, der das Item persönlich zurückgegeben hat? Das könnte sich etwas schwieriger gestalten und wie sollte dann der Owner den User eintragen?

2023-01-11 18:53 UTC, Tonybodo commented
So wie ich das jetzt verstehe passt die aktuelle Implementierung. In der Ausleihhistorie wird dann der Item Owner als derjenige getrackt, der das Item zurück gegeben hat.

2023-01-11 19:03 UTC, DefineDan commented
Also wenn das Datenmodell dafür angepasst werden muss, dann würde ich das erstmal sein lassen. Aber wenn es mit dem jetzigen so geht, wie ich das beschrieben habe, dann sollten wir das einfach mitspeichern. Ich review später noch das UI.

2023-01-12 08:46 UTC, TimRiedel requested changes
All in all a great feature so far! I like the variety of the tests for the `owner_can_return` method, in my opinion all tests for this method are covered.
There are a few things that I would like to discuss or fix before merging, that includes changing the `give_back` method where the lending is completed and writing a test for it, maybe changing the `owner_can_return` method and changing a small typo in the test descriptions in `features/items/show_spec.rb`.

2023-01-12 18:24 UTC, TimRiedel approved these changes
All fine now, works really well! 👍🏼

2023-01-12 18:28 UTC, merged