Cl/personal groups restriction
hpi-swt2/bookkeeper-portal-red pull request #365
Opened 2023-01-30 13:01 UTC by konrad-gerlach

closes #259

2023-01-30 14:03 UTC, konrad-gerlach commented
Sadly as this is (mostly) a backend issue, the best way to test it is to manually create Users in the Database (using rails console) and trying to delete their personal_groups or adding new members to them. To test the front end you should change you user's membership in his personal_group to have admin rights and then go to the user's edit page.

2023-01-30 15:16 UTC, DefineDan approved these changes
From a UI perspective, this seems to be fine. I will trust you regarding the rest ;)

2023-01-31 09:00 UTC, janiswehen commented on app/models/membership.rb
> +  end
Destroy the group here explicitly instead of using dependent destroy but only if its a personal group.

2023-01-31 15:19 UTC, janiswehen requested changes
Good implementation and detailed tests. Well done.
I only have two comments on the naming of the tests.

2023-01-31 15:19 UTC, janiswehen commented on spec/models/user_spec.rb
> +  it "personal group is destroyed when user is destroyed" do
The tests should read as a sentence. i.e. `it "destroys the personal group when the user is destroyed"`

2023-01-31 15:19 UTC, janiswehen commented on spec/models/user_spec.rb
> +  it "shared groups are not destroyed when user is destroyed" do
Same here

2023-01-31 17:55 UTC, janiswehen approved these changes
Well done :)

2023-01-31 17:56 UTC, merged