item lending history
hpi-swt2/bookkeeper-portal-red pull request #374
Opened 2023-01-31 13:33 UTC by gwauge

Show history of all lendings of an item on its page.
Resolves #230

2023-01-31 15:37 UTC, gwauge commented
@MaxSpeer denkst du es soll nur das Datum gerendert werden? Ich habe mich an der Analytics Seite orientiert und dort wurde es so gemacht.

2023-02-01 13:08 UTC, MatthiasCr requested changes
rest looks good!

2023-02-01 13:08 UTC, MatthiasCr commented on app/views/items/show.html.erb
> +          </tr>
please add internalization for columns. Also would recommend renaming "User" to "Borrowed by"

2023-02-01 13:17 UTC, MatthiasCr approved these changes
top looks good!

2023-02-01 13:33 UTC, MaxSpeer commented
Kannst du bitte den Abstand der History nach oben etwas erhöhen?
Außerdem sollte die Kopfzeile der Tabelle vielleicht grau hinterlegt sein.

2023-02-01 13:34 UTC, MaxSpeer commented
Kannst du außerdem bitte die Sortierreihenfolge ändern, sodass die neusten Einträge oben sind?

2023-02-01 14:04 UTC, merged